INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  #  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHT: r"E:\Projects\maskrcnn-benchmark\RNN_OUT_DIR_vertexOnly\model_0010000.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_RNN_HEAD:
    BOX_ENLARGE_RATIO : 0.25
    FEATURE_EXTRACTOR : "RNNFPNFeatureExtractor"
    POOLER_RESOLUTION : 28
    POOLER_SAMPLING_RATIO : 2
    POOLER_SCALES : (0.25, 0.125, 0.0625, 0.03125)
    CONV_LAYERS : (256, 256, 256, 256)
    USE_GN : False
    USE_BN : True
    DILATION : 1
    MAX_LEN: 71
    HIDDEN_DIM : [64,16]
    KERNEL_SIZE : 3
    N_LSTM_LAYERS : 2

    SAMPLE_NUM: 2

    TRAIN_TEMP : 0.
    TRAIN_BEAM_SIZE: 1
    TRAIN_FP_BEAM_SIZE: 1

    TEST_TEMP: 0.
    TEST_BEAM_SIZE: 1
    TEST_FP_BEAM_SIZE: 1

    RETURN_ATTENTION: False
    DT_THRESOLD: 2

    FP_VERTEX_WEIGHT: 200
    FP_EDGE_WEIGHT: 200
    SOFT_VERTEX_LABEL: False
    SOFT_EDGE_LABEL: False
    VERTEX_SOFT_VALUE: 0.7
    EDGE_SOFT_VALUE: 0.8
  VERTEX_ON: True
  VERTEX_ONLY: True
DATASETS:
  TRAIN: ("coco_verOnly",)
  TEST: ("coco_verOnly",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 10001
  CHECKPOINT_PERIOD: 1000
  TEST_PERIOD: 0
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: r"E:\Projects\maskrcnn-benchmark\RNN_OUT_DIR_vertexOnly_v1"
DTYPE: "float32"


